# Generated by Django 3.1 on 2020-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_by',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paytm', 'Paytm'), ('Debit/Credit Card', 'Debit/Credit Card')], default='Cash On Delivery', max_length=20),
        ),
    ]
