# Generated by Django 3.1 on 2020-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20201208_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='Mobile_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
