# Generated by Django 3.1 on 2020-12-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_auto_20201209_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
